### ISSUE TITLE
calcFishTank 수조 정렬

### ISSUE THREAD

**Issue by pannchat** [pannchat/fishhi#1]
![image](https://user-images.githubusercontent.com/49192400/134769553-671532b6-243d-4c79-93e4-eaef2dfab775.png)
가로 60, 세로 30, 깊이 30
![image](https://user-images.githubusercontent.com/49192400/134769580-686f681d-2f36-4d82-84d0-f46e12362d56.png)
가로 30, 세로 30, 깊이 60

어항이 회전할 때 정면의 width 가 될 수 있는 가로와 깊이가 한쪽보다 클 경우 회전축이 정 가운데에 있지 않기 때문에 
```

    // 수조 가운데 정렬

    face.forEach(
        (el) =>{
            if(tankWidth>tankDepth){
                el.style.left = (containerWidth/2) - (front.clientWidth/2) + "px";
            }
            else if(tankWidth<tankDepth){
                el.style.left = (containerWidth - Math.min(front.clientWidth,right.clientWidth))/2 + "px";
            }
            else{
                el.style.left = (containerWidth - Math.min(front.clientWidth,right.clientWidth))/2 + "px";
            }
            
            el.style.top = (containerHeight -front.clientHeight)/2 + "px";
        }
        
        );
```
기존 코드에서 처럼 수조 가운데 정렬이 별도로 필요합니다.

**Comment by chap95** [comment]
@pannchat 
***
아직 다 옮긴게 아니라서 빨리 추가적인 로직 옮겨놓도록 하겠습니다!!
