### ISSUE TITLE
searchPage 구성관련

### ISSUE THREAD

**Issue by chap95** [pannchat/fishhi#2]
@pannchat 
***
 > 우리 검색 결과화면 어캐 띄워야 할지 회의해서 논의해야함
 > 추가적으로 URL encode 해야 할 듯??

**Comment by pannchat** [comment]
저는 디자인이 문제네여

**Comment by chap95** [comment]
일단은 search 는 나중에 생각합시다
issue 정리해서 다시 올릴게
